[project]
name = "voo-router"
version = "0.1.0"
description = "Manage the Port Forwarding settings of your VOO Router"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
